using Clinic.Application.Features.Appointments;
using Clinic.Application.Features.Cashier;
using Clinic.Application.Features.Catalog.Departments;
using Clinic.Application.Features.Catalog.Devices;
using Clinic.Application.Features.Catalog.Queries;
using Clinic.Application.Features.Catalog.Services;
using Clinic.Application.Features.Catalog.Specializations;
using Clinic.Application.Features.ClinicalRecords;
using Clinic.Application.Features.Discounts;
using Clinic.Application.Features.Identity.Authentication;
using Clinic.Application.Features.Identity.Secretaries;
using Clinic.Application.Features.Patients;
using Clinic.Application.Features.Packages;
using Clinic.Application.Features.Scheduling.Closures;
using Clinic.Application.Features.Scheduling.Doctors;
using Clinic.Application.Features.Scheduling.Exceptions;
using Clinic.Application.Features.Scheduling.Queries;
using Clinic.Application.Features.Scheduling.Schedules;
using Microsoft.Extensions.DependencyInjection;

namespace Clinic.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);

        services.AddScoped<LoginCommandHandler>();
        services.AddScoped<LogoutCommandHandler>();
        services.AddScoped<GetCurrentUserQueryHandler>();
        services.AddScoped<ChangePasswordCommandHandler>();
        services.AddScoped<CreateSecretaryCommandHandler>();
        services.AddScoped<ListSecretariesQueryHandler>();
        services.AddScoped<DisableSecretaryCommandHandler>();
        services.AddScoped<EnableSecretaryCommandHandler>();
        services.AddScoped<UnlockSecretaryCommandHandler>();
        services.AddScoped<ResetSecretaryPasswordCommandHandler>();
        services.AddScoped<CreateDepartmentCommandHandler>();
        services.AddScoped<UpdateDepartmentCommandHandler>();
        services.AddScoped<ArchiveDepartmentCommandHandler>();
        services.AddScoped<CreateSpecializationCommandHandler>();
        services.AddScoped<UpdateSpecializationCommandHandler>();
        services.AddScoped<ArchiveSpecializationCommandHandler>();
        services.AddScoped<CreateDeviceCommandHandler>();
        services.AddScoped<UpdateDeviceCommandHandler>();
        services.AddScoped<ArchiveDeviceCommandHandler>();
        services.AddScoped<CreateServiceCommandHandler>();
        services.AddScoped<UpdateServiceCommandHandler>();
        services.AddScoped<ChangeServicePriceCommandHandler>();
        services.AddScoped<ReplaceServiceDevicesCommandHandler>();
        services.AddScoped<ArchiveServiceCommandHandler>();
        services.AddScoped<ListDepartmentsQueryHandler>();
        services.AddScoped<ListSpecializationsQueryHandler>();
        services.AddScoped<ListServicesQueryHandler>();
        services.AddScoped<ListDevicesQueryHandler>();
        services.AddScoped<GetServiceQueryHandler>();
        services.AddScoped<ListServicePriceHistoryQueryHandler>();
        services.AddScoped<CreateDoctorCommandHandler>();
        services.AddScoped<UpdateDoctorCommandHandler>();
        services.AddScoped<ReplaceDoctorServicesCommandHandler>();
        services.AddScoped<ArchiveDoctorCommandHandler>();
        services.AddScoped<CreateDoctorScheduleCommandHandler>();
        services.AddScoped<UpdateDoctorScheduleCommandHandler>();
        services.AddScoped<DeactivateDoctorScheduleCommandHandler>();
        services.AddScoped<CreateDoctorExceptionCommandHandler>();
        services.AddScoped<CancelDoctorExceptionCommandHandler>();
        services.AddScoped<CreateDepartmentClosureCommandHandler>();
        services.AddScoped<CancelDepartmentClosureCommandHandler>();
        services.AddScoped<ListDoctorsQueryHandler>();
        services.AddScoped<GetDoctorQueryHandler>();
        services.AddScoped<ListDoctorSchedulesQueryHandler>();
        services.AddScoped<ListDoctorExceptionsQueryHandler>();
        services.AddScoped<GetDepartmentAvailabilityQueryHandler>();
        services.AddScoped<ListDepartmentClosuresQueryHandler>();
        services.AddScoped<CreatePatientCommandHandler>();
        services.AddScoped<UpdatePatientCommandHandler>();
        services.AddScoped<ArchivePatientCommandHandler>();
        services.AddScoped<CreatePatientNoteCommandHandler>();
        services.AddScoped<ArchivePatientNoteCommandHandler>();
        services.AddScoped<CreateTreatmentHistoryCommandHandler>();
        services.AddScoped<ArchiveTreatmentHistoryCommandHandler>();
        services.AddScoped<ListPatientsQueryHandler>();
        services.AddScoped<GetPatientQueryHandler>();
        services.AddScoped<ListPatientNotesQueryHandler>();
        services.AddScoped<ListTreatmentHistoryQueryHandler>();
        services.AddScoped<CheckAppointmentAvailabilityQueryHandler>();
        services.AddScoped<CreateAppointmentCommandHandler>();
        services.AddScoped<UpdateAppointmentCommandHandler>();
        services.AddScoped<ChangeAppointmentStateCommandHandler>();
        services.AddScoped<RevalidateSuspendedAppointmentsCommandHandler>();
        services.AddScoped<TransferAppointmentDoctorCommandHandler>();
        services.AddScoped<GetAppointmentQueryHandler>();
        services.AddScoped<GetAppointmentCalendarQueryHandler>();
        services.AddScoped<SearchAppointmentsQueryHandler>();
        services.AddScoped<GetShiftPolicyQueryHandler>();
        services.AddScoped<UpdateShiftPolicyCommandHandler>();
        services.AddScoped<ListCashDrawersQueryHandler>();
        services.AddScoped<GenerateShiftsCommandHandler>();
        services.AddScoped<UpdateShiftCommandHandler>();
        services.AddScoped<ExtendShiftCommandHandler>();
        services.AddScoped<CancelShiftCommandHandler>();
        services.AddScoped<RecordOpeningBalanceCommandHandler>();
        services.AddScoped<ReconcileShiftCommandHandler>();
        services.AddScoped<CloseShiftCommandHandler>();
        services.AddScoped<GetShiftQueryHandler>();
        services.AddScoped<GetCurrentShiftQueryHandler>();
        services.AddScoped<SearchShiftsQueryHandler>();
        services.AddScoped<GetShiftHistoryQueryHandler>();
        services.AddScoped<PostPaymentCommandHandler>();
        services.AddScoped<ListPaymentMethodsQueryHandler>();
        services.AddScoped<GetPaymentQueryHandler>();
        services.AddScoped<ListShiftPaymentsQueryHandler>();
        services.AddScoped<GetShiftCollectionSummaryQueryHandler>();
        services.AddScoped<CreateCancellationApprovalCommandHandler>();
        services.AddScoped<ApproveApprovalRequestCommandHandler>();
        services.AddScoped<RejectApprovalRequestCommandHandler>();
        services.AddScoped<GetApprovalRequestQueryHandler>();
        services.AddScoped<SearchApprovalRequestsQueryHandler>();
        services.AddScoped<ExecuteRefundCommandHandler>();
        services.AddScoped<GetRefundQueryHandler>();
        services.AddScoped<ListShiftRefundsQueryHandler>();
        services.AddScoped<CreatePrescriptionDraftCommandHandler>();
        services.AddScoped<SavePrescriptionDraftCommandHandler>();
        services.AddScoped<FinalizePrescriptionCommandHandler>();
        services.AddScoped<CorrectPrescriptionCommandHandler>();
        services.AddScoped<VoidPrescriptionCommandHandler>();
        services.AddScoped<CancelFollowUpCommandHandler>();
        services.AddScoped<GetPrescriptionQueryHandler>();
        services.AddScoped<ListPatientPrescriptionsQueryHandler>();
        services.AddScoped<ListPrescriptionRevisionsQueryHandler>();
        services.AddScoped<GetPrescriptionRevisionQueryHandler>();
        services.AddScoped<GetFollowUpQueryHandler>();
        services.AddScoped<SearchFollowUpsQueryHandler>();
        services.AddScoped<CreatePackageCommandHandler>();
        services.AddScoped<UpdatePackageCommandHandler>();
        services.AddScoped<SetPackageActivationCommandHandler>();
        services.AddScoped<ArchivePackageCommandHandler>();
        services.AddScoped<SearchAdminPackagesQueryHandler>();
        services.AddScoped<GetAdminPackageQueryHandler>();
        services.AddScoped<SearchAvailablePackagesQueryHandler>();
        services.AddScoped<GetAvailablePackageQueryHandler>();
        services.AddScoped<RegisterPatientPackageCommandHandler>();
        services.AddScoped<ExtendPatientPackageCommandHandler>();
        services.AddScoped<ListPatientPackagesQueryHandler>();
        services.AddScoped<GetPatientPackageQueryHandler>();
        services.AddScoped<ListPackageSessionsQueryHandler>();
        services.AddScoped<GetPackageBookingOptionsQueryHandler>();
        services.AddScoped<SearchAdminPatientPackagesQueryHandler>();
        services.AddScoped<CreateDiscountCommandHandler>();
        services.AddScoped<UpdateDiscountCommandHandler>();
        services.AddScoped<SetDiscountActivationCommandHandler>();
        services.AddScoped<ArchiveDiscountCommandHandler>();
        services.AddScoped<GetDiscountQueryHandler>();
        services.AddScoped<SearchDiscountsQueryHandler>();

        return services;
    }
}
